## Student grade Prediction

In [1]:
# importing libraries
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle

In [2]:
# reading dataset
data = pd.read_csv("student-mat.csv")
data.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [3]:
# creating x and y
data = data[["G1", "G2", "G3", "studytime", "failures", "absences"]]
predict = "G3"
x = np.array(data.drop([predict], 1))
y = np.array(data[predict])

In [6]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)

In [4]:
# creating linear regression
linear_regression = LinearRegression()
linear_regression.fit(xtrain, ytrain)
accuracy = linear_regression.score(xtest, ytest)
print(accuracy)

0.8471756555579347


In [5]:
# predicting grades of students
predictions = linear_regression.predict(xtest)
for i in range(len(predictions)):
    print(predictions[x], xtest[x], [ytest[x]])

[[ 7.44373701  8.65750553  9.63590416  7.02921427  8.65750553]
 [ 7.44373701  7.44373701  9.63590416  7.02921427 16.37878638]
 [12.73099839 18.46295856  9.63590416 16.39182175 14.16694682]
 ...
 [14.16694682 18.46295856 11.24051658 16.39182175 16.39182175]
 [18.33037735  9.41996799 11.24051658  7.02921427  7.02921427]
 [18.46295856 15.10715597 11.24051658  7.02921427  7.44373701]] [[[ 8  9  1  3  0]
  [ 8  9  1  0  8]
  [10 10  2  0  4]
  [ 9  7  2  0 18]
  [ 8  9  1  0  8]]

 [[ 8  9  1  3  0]
  [ 8  9  1  3  0]
  [10 10  2  0  4]
  [ 9  7  2  0 18]
  [17 16  2  0  0]]

 [[11 13  1  1 10]
  [18 18  3  0  5]
  [10 10  2  0  4]
  [16 16  1  0  0]
  [15 14  3  0  6]]

 ...

 [[15 14  3  0  6]
  [18 18  3  0  5]
  [11 12  3  1  4]
  [16 16  1  0  0]
  [16 16  1  0  0]]

 [[18 18  4  0  6]
  [ 9 10  2  0  2]
  [11 12  3  1  4]
  [ 9  7  2  0 18]
  [ 9  7  2  0 18]]

 [[18 18  3  0  5]
  [15 15  2  0  0]
  [11 12  3  1  4]
  [ 9  7  2  0 18]
  [ 8  9  1  3  0]]] [array([[10, 10, 10,  6, 10]

[[ 7.44373701  8.65750553  9.63590416  7.02921427  8.65750553]
 [ 7.44373701  7.44373701  9.63590416  7.02921427 16.37878638]
 [12.73099839 18.46295856  9.63590416 16.39182175 14.16694682]
 ...
 [14.16694682 18.46295856 11.24051658 16.39182175 16.39182175]
 [18.33037735  9.41996799 11.24051658  7.02921427  7.02921427]
 [18.46295856 15.10715597 11.24051658  7.02921427  7.44373701]] [[[ 8  9  1  3  0]
  [ 8  9  1  0  8]
  [10 10  2  0  4]
  [ 9  7  2  0 18]
  [ 8  9  1  0  8]]

 [[ 8  9  1  3  0]
  [ 8  9  1  3  0]
  [10 10  2  0  4]
  [ 9  7  2  0 18]
  [17 16  2  0  0]]

 [[11 13  1  1 10]
  [18 18  3  0  5]
  [10 10  2  0  4]
  [16 16  1  0  0]
  [15 14  3  0  6]]

 ...

 [[15 14  3  0  6]
  [18 18  3  0  5]
  [11 12  3  1  4]
  [16 16  1  0  0]
  [16 16  1  0  0]]

 [[18 18  4  0  6]
  [ 9 10  2  0  2]
  [11 12  3  1  4]
  [ 9  7  2  0 18]
  [ 9  7  2  0 18]]

 [[18 18  3  0  5]
  [15 15  2  0  0]
  [11 12  3  1  4]
  [ 9  7  2  0 18]
  [ 8  9  1  3  0]]] [array([[10, 10, 10,  6, 10]

 [18.46295856 15.10715597 11.24051658  7.02921427  7.44373701]] [[[ 8  9  1  3  0]
  [ 8  9  1  0  8]
  [10 10  2  0  4]
  [ 9  7  2  0 18]
  [ 8  9  1  0  8]]

 [[ 8  9  1  3  0]
  [ 8  9  1  3  0]
  [10 10  2  0  4]
  [ 9  7  2  0 18]
  [17 16  2  0  0]]

 [[11 13  1  1 10]
  [18 18  3  0  5]
  [10 10  2  0  4]
  [16 16  1  0  0]
  [15 14  3  0  6]]

 ...

 [[15 14  3  0  6]
  [18 18  3  0  5]
  [11 12  3  1  4]
  [16 16  1  0  0]
  [16 16  1  0  0]]

 [[18 18  4  0  6]
  [ 9 10  2  0  2]
  [11 12  3  1  4]
  [ 9  7  2  0 18]
  [ 9  7  2  0 18]]

 [[18 18  3  0  5]
  [15 15  2  0  0]
  [11 12  3  1  4]
  [ 9  7  2  0 18]
  [ 8  9  1  3  0]]] [array([[10, 10, 10,  6, 10],
       [10, 10, 10,  6, 16],
       [13, 19, 10, 15, 14],
       ...,
       [14, 19, 11, 15, 15],
       [18,  9, 11,  6,  6],
       [19, 15, 11,  6, 10]], dtype=int64)]
[[ 7.44373701  8.65750553  9.63590416  7.02921427  8.65750553]
 [ 7.44373701  7.44373701  9.63590416  7.02921427 16.37878638]
 [12.73099839 18.462

[[ 7.44373701  8.65750553  9.63590416  7.02921427  8.65750553]
 [ 7.44373701  7.44373701  9.63590416  7.02921427 16.37878638]
 [12.73099839 18.46295856  9.63590416 16.39182175 14.16694682]
 ...
 [14.16694682 18.46295856 11.24051658 16.39182175 16.39182175]
 [18.33037735  9.41996799 11.24051658  7.02921427  7.02921427]
 [18.46295856 15.10715597 11.24051658  7.02921427  7.44373701]] [[[ 8  9  1  3  0]
  [ 8  9  1  0  8]
  [10 10  2  0  4]
  [ 9  7  2  0 18]
  [ 8  9  1  0  8]]

 [[ 8  9  1  3  0]
  [ 8  9  1  3  0]
  [10 10  2  0  4]
  [ 9  7  2  0 18]
  [17 16  2  0  0]]

 [[11 13  1  1 10]
  [18 18  3  0  5]
  [10 10  2  0  4]
  [16 16  1  0  0]
  [15 14  3  0  6]]

 ...

 [[15 14  3  0  6]
  [18 18  3  0  5]
  [11 12  3  1  4]
  [16 16  1  0  0]
  [16 16  1  0  0]]

 [[18 18  4  0  6]
  [ 9 10  2  0  2]
  [11 12  3  1  4]
  [ 9  7  2  0 18]
  [ 9  7  2  0 18]]

 [[18 18  3  0  5]
  [15 15  2  0  0]
  [11 12  3  1  4]
  [ 9  7  2  0 18]
  [ 8  9  1  3  0]]] [array([[10, 10, 10,  6, 10]

 [18.46295856 15.10715597 11.24051658  7.02921427  7.44373701]] [[[ 8  9  1  3  0]
  [ 8  9  1  0  8]
  [10 10  2  0  4]
  [ 9  7  2  0 18]
  [ 8  9  1  0  8]]

 [[ 8  9  1  3  0]
  [ 8  9  1  3  0]
  [10 10  2  0  4]
  [ 9  7  2  0 18]
  [17 16  2  0  0]]

 [[11 13  1  1 10]
  [18 18  3  0  5]
  [10 10  2  0  4]
  [16 16  1  0  0]
  [15 14  3  0  6]]

 ...

 [[15 14  3  0  6]
  [18 18  3  0  5]
  [11 12  3  1  4]
  [16 16  1  0  0]
  [16 16  1  0  0]]

 [[18 18  4  0  6]
  [ 9 10  2  0  2]
  [11 12  3  1  4]
  [ 9  7  2  0 18]
  [ 9  7  2  0 18]]

 [[18 18  3  0  5]
  [15 15  2  0  0]
  [11 12  3  1  4]
  [ 9  7  2  0 18]
  [ 8  9  1  3  0]]] [array([[10, 10, 10,  6, 10],
       [10, 10, 10,  6, 16],
       [13, 19, 10, 15, 14],
       ...,
       [14, 19, 11, 15, 15],
       [18,  9, 11,  6,  6],
       [19, 15, 11,  6, 10]], dtype=int64)]
[[ 7.44373701  8.65750553  9.63590416  7.02921427  8.65750553]
 [ 7.44373701  7.44373701  9.63590416  7.02921427 16.37878638]
 [12.73099839 18.462

  [ 8  9  1  3  0]]] [array([[10, 10, 10,  6, 10],
       [10, 10, 10,  6, 16],
       [13, 19, 10, 15, 14],
       ...,
       [14, 19, 11, 15, 15],
       [18,  9, 11,  6,  6],
       [19, 15, 11,  6, 10]], dtype=int64)]
[[ 7.44373701  8.65750553  9.63590416  7.02921427  8.65750553]
 [ 7.44373701  7.44373701  9.63590416  7.02921427 16.37878638]
 [12.73099839 18.46295856  9.63590416 16.39182175 14.16694682]
 ...
 [14.16694682 18.46295856 11.24051658 16.39182175 16.39182175]
 [18.33037735  9.41996799 11.24051658  7.02921427  7.02921427]
 [18.46295856 15.10715597 11.24051658  7.02921427  7.44373701]] [[[ 8  9  1  3  0]
  [ 8  9  1  0  8]
  [10 10  2  0  4]
  [ 9  7  2  0 18]
  [ 8  9  1  0  8]]

 [[ 8  9  1  3  0]
  [ 8  9  1  3  0]
  [10 10  2  0  4]
  [ 9  7  2  0 18]
  [17 16  2  0  0]]

 [[11 13  1  1 10]
  [18 18  3  0  5]
  [10 10  2  0  4]
  [16 16  1  0  0]
  [15 14  3  0  6]]

 ...

 [[15 14  3  0  6]
  [18 18  3  0  5]
  [11 12  3  1  4]
  [16 16  1  0  0]
  [16 16  1  0  0]]
